// KaTeX macros shared by every chapter, so notation is spelled one way in the
// whole book. The notation appendix documents each of them.

export const MACROS: Record<string, string> = {
  "\\R": "\\mathbb{R}",
  "\\E": "\\mathbb{E}",
  "\\Prob": "\\mathbb{P}",
  "\\Var": "\\operatorname{Var}",
  "\\Cov": "\\operatorname{Cov}",
  "\\N": "\\mathcal{N}",
  "\\GP": "\\mathcal{GP}",
  "\\X": "\\mathcal{X}",
  "\\D": "\\mathcal{D}",
  "\\KL": "\\operatorname{KL}",
  "\\tr": "\\operatorname{tr}",
  "\\diag": "\\operatorname{diag}",
  "\\argmax": "\\operatorname*{arg\\,max}",
  "\\argmin": "\\operatorname*{arg\\,min}",
  "\\dd": "\\mathrm{d}",
  "\\T": "\\top",
  "\\given": "\\,\\vert\\,",
  "\\bm": "\\boldsymbol{#1}",
  "\\vx": "\\mathbf{x}",
  "\\vy": "\\mathbf{y}",
  "\\vf": "\\mathbf{f}",
  "\\vk": "\\mathbf{k}",
  "\\vz": "\\mathbf{z}",
  "\\vw": "\\mathbf{w}",
  "\\va": "\\mathbf{a}",
  "\\vb": "\\mathbf{b}",
  "\\ve": "\\mathbf{e}",
  "\\vu": "\\mathbf{u}",
  "\\vv": "\\mathbf{v}",
  "\\vg": "\\mathbf{g}",
  "\\vmu": "\\boldsymbol{\\mu}",
  "\\mK": "\\mathbf{K}",
  "\\mI": "\\mathbf{I}",
  "\\mL": "\\mathbf{L}",
  "\\mW": "\\mathbf{W}",
  "\\mA": "\\mathbf{A}",
  "\\mSigma": "\\boldsymbol{\\Sigma}",
  "\\EI": "\\operatorname{EI}",
  "\\PI": "\\operatorname{PI}",
  "\\UCB": "\\operatorname{UCB}",
  "\\EUBO": "\\operatorname{EUBO}",
  "\\Regret": "\\operatorname{R}",
};
