// Precomputes the simulated exoskeleton tuning sessions shown in the figure
// cs-exo-adapt (chapter "Tuning an Exoskeleton with a Person in the Loop").
// The walker and the tuners are those of src/figures/lib/cs-exo.ts, so the
// precomputed sessions and the interactive figure cs-exo-tune use the same
// model. Nothing here is measured data.
//
//   node tools/figure-data/cs-exo-race.ts > src/figures/lib/cs-exo-race-data.ts
//
// 40 simulated walkers, each once as an adapted (expert) walker with a fixed
// landscape and once as a novice whose landscape changes over the session.
// Six tuners: Bayesian optimization on two-minute metabolic estimates (lower
// confidence bound, exploration constant 2.6), the same with time as a third
// input, the same with exploration constant 0.93, CMA-ES on the same
// estimates, a simulated self-tuner, and preferential Bayesian optimization on
// felt comparisons (run for 60 minutes only). For every even minute up to 120
// the script records the true metabolic reduction of each tuner's current
// recommendation, on the landscape of that moment ("now") and on the fully
// adapted landscape ("later"), and stores the quartiles over walkers.

import { GENERIC, recAt, runBO, runCMA, runPBO, runSelf, walker, type Run, type U } from "../../src/figures/lib/cs-exo.ts";

const WALKERS = 40;
const HORIZON = 120;
const PBO_HORIZON = 60;
const TIMES = Array.from({ length: HORIZON / 2 }, (_, i) => (i + 1) * 2);
const METHODS = ["bo", "boTime", "boExploit", "cma", "self", "pbo"] as const;
type Method = (typeof METHODS)[number];

const quart = (v: number[]) => {
  const s = [...v].sort((a, b) => a - b);
  const q = (p: number) => { const i = (s.length - 1) * p, lo = Math.floor(i), hi = Math.ceil(i); return s[lo] + (s[hi] - s[lo]) * (i - lo); };
  return [q(0.25), q(0.5), q(0.75)].map((x) => Math.round(x * 1000) / 1000);
};

const out: Record<string, unknown> = {};
const t0 = performance.now();
for (const novice of [false, true]) {
  const runs: Record<Method, Run[]> = { bo: [], boTime: [], boExploit: [], cma: [], self: [], pbo: [] };
  const ws = Array.from({ length: WALKERS }, (_, k) => walker(k + 1, novice));
  ws.forEach((w, k) => {
    const s = k + 1;
    runs.bo.push(runBO(w, HORIZON, s));
    runs.boTime.push(runBO(w, HORIZON, s, 2.6, 60));
    runs.boExploit.push(runBO(w, HORIZON, s, 0.93));
    runs.cma.push(runCMA(w, HORIZON, s));
    runs.self.push(runSelf(w, HORIZON, s));
    runs.pbo.push(runPBO(w, PBO_HORIZON, s));
    console.error(`${novice ? "novice" : "expert"} walker ${s} at ${((performance.now() - t0) / 1000).toFixed(0)} s`);
  });
  const key = novice ? "novice" : "expert";
  const series = (f: (w: (typeof ws)[number], k: number, t: number) => number, times = TIMES) => times.map((t) => quart(ws.map((w, k) => f(w, k, t))));
  const data: Record<string, unknown> = {
    best: series((w, _k, t) => w.best(t)),
    generic: series((w, _k, t) => w.reduction(GENERIC as U, t)),
  };
  for (const m of METHODS) {
    const times = m === "pbo" ? TIMES.filter((t) => t <= PBO_HORIZON) : TIMES;
    data[m] = {
      now: series((w, k, t) => w.reduction(recAt(runs[m][k], t), t), times),
      later: series((w, k, t) => w.reduction(recAt(runs[m][k], t), 1e6), times),
    };
  }
  out[key] = data;
}
console.log(`// Generated by tools/figure-data/cs-exo-race.ts; do not edit by hand.
// Simulated exoskeleton tuning sessions: ${WALKERS} simulated walkers, adapted
// (expert) and adapting (novice). For each tuner and every second minute,
// [first quartile, median, third quartile] over walkers of the true metabolic
// reduction of the tuner's current recommendation, on the landscape of that
// moment (now) and on the fully adapted landscape (later). Not measured data.

export const EXO_RACE = ${JSON.stringify({ walkers: WALKERS, times: TIMES, pboHorizon: PBO_HORIZON, ...out })} as const;
`);
