// Precomputes the simulated photo-enhancement sessions shown in the figure
// cs-photo-race (chapter "Enhancing a Photo by Comparison"). Each session
// runs the same model and question rules as the interactive figure
// cs-photo-enhance (src/figures/lib/cs-photo.ts) against the simulated taste
// with seed 7, the figure's default, so the hidden favorite is the same one
// the reader can reveal there.
//
//   node tools/figure-data/cs-photo-race.ts > src/figures/lib/cs-photo-race-data.ts
//
// Four questioners: pairs chosen by EUBO, random pairs, the slider of
// sequential line search as published (from the best design to the design
// with the highest expected improvement), and the slider extended to the
// edges of the box in both directions (the figure's default). Three levels of
// answer noise, a stationary and a drifting taste, 16 sessions each that
// differ in their candidate pools, first edit, and answer noise, 20 answers
// per session. Everything is seeded, so the output is reproducible.

import {
  ORIGINAL, fitLog, gap, nextPair, nextSlider, randomPair, simPair, simSlider, taste, type Entry, type Pt,
} from "../../src/figures/lib/cs-photo.ts";
import { rng } from "../../src/figures/lib/random.ts";

const TASTE_SEED = 7;
const FORMS = ["eubo", "random", "segment", "line"] as const;
const NOISES = [0.05, 0.1, 0.25];
const RUNS = 16;
const STEPS = 20;

type Form = (typeof FORMS)[number];

function session(form: Form, noise: number, drifting: boolean, run: number) {
  const tz = taste(TASTE_SEED, drifting, STEPS);
  const r = rng(run * 7919 + Math.round(noise * 1000) * 31 + (drifting ? 17 : 0) + FORMS.indexOf(form) * 101);
  const qseed = 100 + run;
  const es: Entry[] = [];
  const gaps: number[] = [];
  for (let s = 0; s < STEPS; s++) {
    const m = fitLog(es);
    if (form === "segment" || form === "line") {
      const { a, b } = nextSlider(m, qseed, es.length, form);
      es.push({ kind: "slider", a, b, t: Math.round(simSlider(tz, a, b, noise, r, s) * 100) / 100 });
    } else {
      const [a, b] = form === "eubo" ? nextPair(m, qseed, es.length) : randomPair(m, qseed, es.length);
      const aw = simPair(tz, a, b, noise, r, s);
      es.push({ kind: "pair", w: aw ? a : b, l: aw ? b : a, rep: false });
    }
    // the gap is measured against the taste as it is after this answer
    gaps.push(gap(tz, fitLog(es).best, s + 1));
  }
  return { gaps, final: fitLog(es).best };
}

const r3 = (v: number) => Math.round(v * 1000) / 1000;
const out: Record<string, { gaps: number[][]; final: Pt[] }> = {};
const t0 = performance.now();
for (const drifting of [false, true]) for (const noise of NOISES) for (const form of FORMS) {
  const runs = Array.from({ length: RUNS }, (_, k) => session(form, noise, drifting, k + 1));
  out[`${form}|${noise}|${drifting ? 1 : 0}`] = { gaps: runs.map((x) => x.gaps.map(r3)), final: runs.map((x) => x.final.map(r3)) };
  console.error(`${form} noise=${noise} drift=${drifting} done at ${((performance.now() - t0) / 1000).toFixed(0)} s`);
}
const still = taste(TASTE_SEED, false, STEPS), moving = taste(TASTE_SEED, true, STEPS);
const data = {
  tasteSeed: TASTE_SEED, steps: STEPS, runs: RUNS, noises: NOISES, forms: FORMS,
  fav0: still.favorite(0).map(r3), fav1: moving.favorite(STEPS).map(r3),
  gapOriginal: r3(gap(still, ORIGINAL)), sessions: out,
};
console.log(`// Generated by tools/figure-data/cs-photo-race.ts; do not edit by hand.
// Simulated photo-enhancement sessions against the simulated taste with seed
// ${TASTE_SEED}: ${FORMS.length} questioners x ${NOISES.length} noise levels x stationary or drifting taste
// x ${RUNS} sessions x ${STEPS} answers. gaps[run][step] is the utility gap of the
// recommendation after step + 1 answers; final[run] is the last recommendation.

export const RACE = ${JSON.stringify(data)} as const;
`);
